apiVersion: v1
kind: Service
metadata:
  name: hacker-suitcases-mysql
spec:
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
  - name: mysql
    port: {{ .Values.mysql.service.port }}
    targetPort: 3306
  type: {{ .Values.mysql.service.type }}

