apiVersion: v1
kind: Service
metadata:
  name: hacker-suitcases-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - name: http
    port: {{ .Values.app.service.port }}
    targetPort: 8082
  type: {{ .Values.app.service.type }}

